export const productData = [
  {
    id: 1,
    title: "Single Room",
    price: "20 for 24 Hour",
    description: "A cozy Single Room, perfect for solo travelers looking for comfort and convenience. It includes a comfortable twin bed, free Wi-Fi, a work desk, and a private bathroom. Ideal for business trips or short stays.",
    category: "Rooms",
    image: "https://thumbs.dreamstime.com/z/single-hotel-room-bed-desk-wardrobe-single-hotel-room-bed-desk-wardrobe-high-quality-photo-316204496.jpg",
    rating: { rate: 3.9 },
  },
  {
    id: 2,
    title: "Single Room",
    price: "20 for 24 Hour",
    description: "Our Single Room offers privacy and relaxation for the solo traveler. Features include a twin bed, complimentary toiletries, air conditioning, and a flat-screen TV. Room service is available.",
    category: "Rooms",
    image: "https://thumbs.dreamstime.com/z/hotel-room-9223964.jpg",
    rating: { rate: 3.9 },
  },
  {
    id: 3,
    title: "Double Room",
    price: "40 for 24 Hour",
    description: "The Double Room is designed for couples or friends, featuring a double bed, en-suite bathroom, and modern amenities like Wi-Fi and satellite TV. Enjoy complimentary breakfast and access to the hotel's fitness center.",
    category: "Rooms",
    image: "https://thumbs.dreamstime.com/z/standard-double-room-hotel-to-close-distance-shooting-clean-tidy-46535941.jpg",
    rating: { rate: 4.1, count: 259 },
  },
  {
    id: 4,
    title: "Double Room",
    price: "40 for 24 Hour",
    description: "Spacious Double Room with a queen-sized bed, perfect for a relaxing stay. Includes a mini-fridge, safe, and 24-hour room service. Guests can enjoy complimentary parking and access to the spa.",
    category: "Rooms",
    image: "https://thumbs.dreamstime.com/z/beautiful-double-room-12106356.jpg",
    rating: { rate: 4.1, count: 259 },
  },
  {
    id: 5,
    title: "Triple Room",
    price: "50 for 24 Hour",
    description: "Ideal for families or small groups, the Triple Room features three twin beds, a spacious seating area, and a balcony with city views. Additional amenities include a mini-bar, tea/coffee maker, and daily housekeeping.",
    category: "Rooms",
    image: "https://thumbs.dreamstime.com/b/triple-room-hotel-interior-classic-style-36695336.jpg",
    rating: { rate: 4.7, count: 500 },
  },
  {
    id: 6,
    title: "Triple Room",
    price: "50 for 24 Hour",
    description: "The Triple Room offers comfort for three guests, with modern furnishings, premium bedding, and a private balcony. Enjoy a complimentary breakfast buffet and access to the rooftop pool.",
    category: "Rooms",
    image: "https://thumbs.dreamstime.com/z/triple-beds-luxury-hotel-family-room-curtains-triple-beds-luxury-suite-hotel-room-106762767.jpg",
    rating: { rate: 4.7, count: 500 },
  },
  {
    id: 7,
    title: "Standard Room",
    price: "15 for 24 Hour",
    description: "Our budget-friendly Standard Room offers great value without sacrificing comfort. It includes a double bed, free Wi-Fi, a flat-screen TV, and complimentary toiletries. Perfect for budget-conscious travelers.",
    category: "Rooms",
    image: "https://thumbs.dreamstime.com/z/hotel-rooms-19984165.jpg",
    rating: { rate: 2.1, count: 430 },
  },
  {
    id: 8,
    title: "Standard Room",
    price: "15 for 24 Hour",
    description: "The Standard Room offers simplicity and comfort, featuring a queen-sized bed, air conditioning, and a private bathroom with a shower. Guests can enjoy in-room dining and access to the lounge area.",
    category: "Rooms",
    image: "https://thumbs.dreamstime.com/z/hotel-standard-room-23536028.jpg",
    rating: { rate: 2.1, count: 430 },
  },
  {
    id: 9,
    title: "Deluxe Room",
    price: "60 for 24 Hour",
    description: "Our Deluxe Room is an upscale option with a king-sized bed, luxurious linens, and a spacious bathroom. Enjoy complimentary snacks, a minibar, and access to the VIP lounge.",
    category: "Rooms",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTj_uw4zliyzqHzQlLTrMhJSCr1tIU9Vvj59A&s",
    rating: { rate: 4.6, count: 400 },
  },
  {
    id: 10,
    title: "Deluxe Room",
    price: "60 for 24 Hour",
    description: "The Deluxe Room offers superior comfort and elegance, with stunning views, a plush king-sized bed, and high-end toiletries. Perfect for business travelers or those seeking a luxurious stay.",
    category: "Rooms",
    image: "https://thumbs.dreamstime.com/b/hotel-room-19941533.jpg",
    rating: { rate: 4.6, count: 400 },
  },
  {
    id: 11,
    title: "Royal Room",
    price: "80 for 24 Hour",
    description: "The Royal Room offers the ultimate luxury experience, featuring a grand living space, private dining area, and personal concierge service. Includes exclusive access to the executive lounge and a private spa.",
    category: "Room",
    image: "https://thumbs.dreamstime.com/b/sultan-luxurious-royal-bedroom-night-wealthy-middle-east-interior-luxury-oriental-arab-hotel-room-copy-space-generative-ai-324674925.jpg",
    rating: { rate: 3.9, count: 70 },
  },
  {
    id: 12,
    title: "Royal Room",
    price: "80 for 24 Hour",
    description: "A lavish Royal Room with stunning views, featuring multiple rooms, a grand master bedroom, a private jacuzzi, and butler service. Ideal for guests seeking an opulent stay.",
    category: "Room",
    image: "https://thumbs.dreamstime.com/b/sultan-luxurious-royal-bedroom-night-wealthy-middle-east-interior-luxury-oriental-arab-hotel-room-copy-space-generative-ai-325576116.jpg",
    rating: { rate: 3.9, count: 70 },
  },
  {
    id: 13,
    title: "PentHouse",
    price: "100 for 24 Hour",
    description: "The PentHouse is an exclusive luxury accommodation located on the top floor, offering panoramic views, a private terrace, and premium services such as a dedicated concierge and access to a private pool.",
    category: "Room",
    image: "https://thumbs.dreamstime.com/b/penthouse-bedroom-night-dark-gloomy-room-view-city-bed-penthouse-bedroom-night-dark-gloomy-room-323306526.jpg",
    rating: { rate: 3, count: 400 },
  },
  {
    id: 14,
    title: "PentHouse",
    price: "100 for 24 Hour",
    description: "A luxurious PentHouse located on the top floor with exclusive amenities such as a private bar, a home theater, a jacuzzi, and floor-to-ceiling windows. Perfect for those seeking an unforgettable experience.",
    category: "Room",
    image: "https://thumbs.dreamstime.com/b/luxurious-penthouse-bedroom-night-generative-ai-275170640.jpg",
    rating: { rate: 3, count: 400 },
  },
 
];
